# Configuración de Alacritty en formato TOML
# Guarda este archivo en ~/.config/alacritty/alacritty.toml

# Configuración de ventana
[window]
dimensions = { columns = 90, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "full"
opacity = 0.8
dynamic_title = true

# Configuración del cursor
[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
thickness = 0.15

# Fuente - JetBrainsMono Nerd Font
[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

# Colores
[colors.primary]
background = "#2b2b2b"    # Tierra oscura
foreground = "#e0d9c6"    # Piedra caliza clara

[colors.normal]
black = "#373529"      # Tierra fértil
red = "#a75643"        # Arcilla
green = "#7d9551"      # Musgo de bosque
yellow = "#d5a95e"     # Arena dorada
blue = "#6c8da3"       # Lago de montaña
magenta = "#8b7d77"    # Piedra volcánica
cyan = "#5d9d88"       # Aguamarina
white = "#c9c3b7"      # Piedra caliza

[colors.bright]
black = "#5a5448"      # Corteza de árbol
red = "#c57963"        # Terracota
green = "#90a959"      # Pasto fresco
yellow = "#e6bb7f"     # Campo de trigo
blue = "#7eaac7"       # Cielo despejado
magenta = "#a39990"    # Montaña al atardecer
cyan = "#6eb9a1"       # Turquesa natural
white = "#efe9dd"      # Blanco hueso

# Draw bold text with bright colors

# Campana
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Selección
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

# Scroll
[scrolling]
history = 10000

